spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      default_schema: oauth
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 83b5fa90bb8d4538e06e9233b78b30cb
            client-secret: null
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  expiration: 3000
  secret: c29uZ3N1YXBhc3N3b3Jkc2VjcmV0c29uZ3N1YXBhc3N3b3Jkc2VjcmV0c29uZ3N1YXBhc3N3b3Jkc2VjcmV0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
