spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org:
      apache:
        coyote:
          http11: trace
com.akatsuki.newsum: debug  # ← 패키지 경로에 맞게 설정
