spring:
  config:
    activate:
      on-profile: dev
  
  # 데이터베이스 설정 (PostgreSQL)
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  
  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Devtools 설정
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# 로깅 설정
logging:
  level:
    com.akatsuki.newsum: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
