spring:
  config:
    activate:
      on-profile: prod
  
  # 데이터베이스 설정 (PostgreSQL)
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  
  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cache:
    type: redis
    cache-names: webtoons, comments, users
    redis:
      time-to-live: 3600000

# 로깅 설정
logging:
  level:
    com.akatsuki.newsum: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/newsum/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Swagger API 문서 비활성화
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# P6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: false
