spring:
  application:
    name: newsum-be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:file:.env[.properties]
  
  # JPA 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: false
  
  # Jackson 설정
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  
  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.akatsuki.newsum
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui.disable-swagger-default-url: true

# P6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
#
#  # Security 설정
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
#            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
#            authorization-grant-type: authorization_code
#            scope: profile_nickname, profile_image, account_email
#            client-name: Kakao
#            client-authentication-method: client_secret_post
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
## JWT 설정
#jwt:
#  secret: ${JWT_SECRET}
#  expiration: ${JWT_EXPIRATION:86400000}
#  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
#
## 앱 설정
#app:
#  oauth2:
#    authorized-redirect-uris: ${APP_OAUTH2_REDIRECT_URIS:http://localhost:3000/oauth2/redirect}
