spring:
  config:
    activate:
      on-profile: local
  
  # 데이터베이스 설정 (PostgreSQL)
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration