spring:
  application:
    name: newsum-be
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import: optional:file:.env[.properties]

  # JPA 설정
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: false

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.akatsuki.newsum
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui.disable-swagger-default-url: true

# P6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

logging:
  level:
    org:
      apache:
        coyote:
          http11: trace
    root: info

user:
  default-profile-image-url: ${USER_DEFAULT_PROFILE_IMAGE_URL}
