name: Backend Prod Docker CD (Blue-Green)

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

jobs:
# ──────────────────────────────────────────────────────────
# 1️⃣ Build & Push  (GitHub-hosted)
# ──────────────────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    outputs:
      image:  ${{ steps.push.outputs.image }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Build
        run: |
          ./gradlew clean build
          cp build/libs/newsum-0.0.1-SNAPSHOT.jar app.jar   # 루트에 JAR

      # — AWS & ECR 로그인 —
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:             ap-northeast-2

      - name: ECR Docker Login
        run: |
          aws ecr get-login-password --region ap-northeast-2 \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      # — Docker Build & Push —
      - name: Build & Push image
        id: push
        run: |
          IMAGE="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO }}:latest"
          docker build -t "$IMAGE" .
          docker push  "$IMAGE"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

# ──────────────────────────────────────────────────────────
# 2️⃣ Deploy (AZ-1, 타깃 결정 & 출력)
# ──────────────────────────────────────────────────────────
  deploy-az1:
    needs: build
    runs-on: [ self-hosted, linux, ec2-prod-runner ]   # EC2-1
    outputs:
      target: ${{ steps.decide.outputs.target }}

    steps:
      # AWS 로그인 & ECR 로그인
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-2

      - name: ECR Login
        run: |
          aws ecr get-login-password --region ap-northeast-2 \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      # Infisical .env
      - name: Fetch .env
        run: |
          curl -Ls https://${{ secrets.AWS_CLOUDFRONT_URL }}/tools/infisical-linux-amd64 -o infisical
          chmod +x infisical && sudo mv infisical /usr/local/bin/infisical
          infisical export \
            --env=${{ secrets.INFISICAL_ENV_PROD }} \
            --projectId=${{ secrets.INFISICAL_PROJECT_ID }} \
            --token=${{ secrets.INFISICAL_TOKEN_PROD }} \
            --format=dotenv \
            --domain=${{ secrets.INFISICAL_API_URL }} > /tmp/deploy.env

      # 🔍 Blue/Green 결정(EC2 내부)
      - name: Decide target
        id: decide
        run: |
          if docker ps --format '{{.Names}}' | grep -q backend-blue; then
               echo "target=green" >> "$GITHUB_OUTPUT"
               echo "TARGET=green"  >> "$GITHUB_ENV"
          else echo "target=blue"  >> "$GITHUB_OUTPUT"
               echo "TARGET=blue"  >> "$GITHUB_ENV"; fi

      # 배포
      - name: Deploy to AZ-1
        run: |
          cd ${{ secrets.BACKEND_PATH_PROD }}
          cp /tmp/deploy.env .env

          docker compose -f docker-compose-${TARGET}.yml pull
          docker compose -f docker-compose-${TARGET}.yml up -d --remove-orphans

          rm -f .env

# ──────────────────────────────────────────────────────────
# 3️⃣ Deploy (AZ-2, 동일 타깃)
# ──────────────────────────────────────────────────────────
  deploy-az2:
    needs: deploy-az1               # 타깃 값 받아오기
    runs-on: [ self-hosted, linux, ec2-prod-runner ]   # EC2-2
    env:
      TARGET: ${{ needs.deploy-az1.outputs.target }}

    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-2

      - name: ECR Login
        run: |
          aws ecr get-login-password --region ap-northeast-2 \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Fetch .env
        run: |
          curl -Ls https://${{ secrets.AWS_CLOUDFRONT_URL }}/tools/infisical-linux-amd64 -o infisical
          chmod +x infisical && sudo mv infisical /usr/local/bin/infisical
          infisical export \
            --env=${{ secrets.INFISICAL_ENV_PROD }} \
            --projectId=${{ secrets.INFISICAL_PROJECT_ID }} \
            --token=${{ secrets.INFISICAL_TOKEN_PROD }} \
            --format=dotenv \
            --domain=${{ secrets.INFISICAL_API_URL }} > /tmp/deploy.env

      - name: Deploy to AZ-2
        run: |
          cd ${{ secrets.BACKEND_PATH_PROD }}
          cp /tmp/deploy.env .env

          docker compose -f docker-compose-${TARGET}.yml pull
          docker compose -f docker-compose-${TARGET}.yml up -d --remove-orphans

          rm -f .env

# ──────────────────────────────────────────────────────────
# 4️⃣ Switch ALB Listener  (Blue ⇄ Green)
# ──────────────────────────────────────────────────────────
  switch-alb:
    needs: [ deploy-az2 ]
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-2

      - name: Pick TargetGroup ARN
        id: pick
        run: |
          if [ "${{ needs.deploy-az1.outputs.target }}" = "blue" ]; then
               echo "arn=${{ secrets.TG_BLUE_ARN }}"  >> "$GITHUB_OUTPUT"
          else echo "arn=${{ secrets.TG_GREEN_ARN }}" >> "$GITHUB_OUTPUT"; fi

      - name: Switch ALB Listener
        run: |
          aws elbv2 modify-listener \
            --listener-arn ${{ secrets.ALB_LISTENER_ARN }} \
            --default-actions Type=forward,TargetGroupArn=${{ steps.pick.outputs.arn }} \
            --region ap-northeast-2
