name: Backend Dev docker CD

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Install Infisical CLI from CloudFront
        run: |
          curl -L https://${{ secrets.AWS_CLOUDFRONT_URL }}/tools/infisical-linux-amd64 -o infisical
          chmod +x infisical
          sudo mv infisical /usr/local/bin/infisical

      - name: Fetch .env from Infisical
        run: |
          infisical export \
            --env=${{ secrets.INFISICAL_ENV_DEV }} \
            --projectId=${{ secrets.INFISICAL_PROJECT_ID }} \
            --token=${{ secrets.INFISICAL_TOKEN_DEV }} \
            --format=dotenv \
            --domain=${{ secrets.INFISICAL_API_URL }} \
            > .env

      - name: Deploy Spring Boot app with Docker
        run: |
          cd ${{ secrets.BACKEND_PATH_DEV }}

          # 기존 컨테이너 중지 및 제거
          docker compose -f docker-compose.yml down

          # .env 덮어쓰기
          mv $GITHUB_WORKSPACE/.env .env

          # 새 버전 배포
          docker compose -f docker-compose.yml up -d --build

          # 보안상 .env 제거
          rm -f .env
